### ISSUE TITLE
#18 Верстка страницы "Видеоурок"

### ISSUE THREAD

**Issue by Murzaliev-Azamat** [ESDP-JS17-ATTRACTOR/final#29]
# Мотивация

Сверстать страницу "Видеоурок", согласно предоставленному макету, с учетом запланированных сущностей и UI оптимизацией. Страница "Видеоурок" должна предоставлять возможность студенту просмотреть урок, перейти к предыдущему или следующему видеоуроку, а также возможность оставить и прочитать комментарии, относящиеся к данному видеоуроку. Также на данной странице студенту доступна информация какой это по счету урок из данного курса и когда был просмотрен урок. Дата просмотра урока отображается в заголовке страницы.

[Ссылка на макет](https://www.figma.com/file/uiO823XNPsoiDcpGL0uoPI/cloud?node-id=9-2218&t=dYAp6Lk0gdVoY5iW-0)

### Модуль
1.1 Создать сущность "module" со следующими полями:
- уникальный номер (id)
- course_id
- number (порядковый номер)
- title
- description

1.2 CRUD: реализовать возможность создания/чтения/модификации/удаления модуля по запросу на серверную часть.

### Урок
2.1. Создать сущность "lesson" со следующими полями: 

- (id)
- course_id
- module_id (????)
- number (порядковый номер урока)
- title
- description
- video
- isStopLesson : boolean / default: false

2.2 CRUD: реализовать возможность создания/чтения/модификации/удаления урока по запросу на серверную часть.
2.3 Реализовать возможность сохранения видеофайла для урока (установка и конфигурация multer)

### Урок пользователя (user's lesson)
3.1 Создать сущность "users_lesson" со следующими полями
- id
- student (user_id)
- lesson (lesson_id)
- isViewed (boolean)
- isAvailable (boolean)
- isStopLesson (boolean)

3.2 CRUD: реализовать возможность создания/чтения/модификации/удаления урока пользователя по запросу на серверную часть.

### Покупка
4.1  Создать сущность "purchase" со следующими полями:
- id
- customer (user_id)
- course (course_id)
- purchasedAt (дата покупки курса)
- closedAt - дата закрытия доступа к курсу (начало курса + длительность курса + какое-то время для доступа к курсу после его окончания)

4.2 CRUD: реализовать возможность создания/чтения/удаления покупки пользователя по запросу на серверную часть.

### Комментарий
4.1 Создать сущность "comment" со следующими полями:
- id
- user (user_id)
- lesson (lesson_id)
- text (сам комментарий)

4.2 CRUD: реализовать возможность создания/чтения/удаления комментария, а также чтения всех комментариев, относящихся к данному уроку по запросу на серверную часть.

### Фикстуры
Создать фикстуры для следующих сущностей:
- User
- Category
- Course
- CourseModule
- Lesson
- Purchase
- UsersLesson

### Согласно макету:

Страница, доступная студенту должна содержать один видеоурок и следующую информацию:
1. Заголовок (название урока, дата просмотра данного урока студентом)
2. Порядковый номер урока 
3. Две ссылки "Previous lesson" и "Next lesson" для перехода от одного видео к другому
4. Описание
5. Видеоурок.
6. Форму для отправки комментария пользователем:
- аватар студента
- текстовое поле
- кнопка отправки сообщения

# Расчетное время

12 часов

# Затраченное время

30 часов

**Comment by salvorg** [comment]
Ввиду некоторых изменений от заказчика, пришлось менять связи в базе данных и переделывать CRUD контроллеров. Тикет пополнился новыми задачами и затраченное время превысило расчетное.
