### ISSUE TITLE
#20 Отображение текущего языка в селекторе смены языков

### ISSUE THREAD

**Issue by Murzaliev-Azamat** [ESDP-JS17-ATTRACTOR/final#31]
# Мотивация

Ввиду неправильного отображения текущего языка в "шапке" сайта, принято решение переписать код и связать его с  отображаемой версией сайта

# Планируемая реализация

## Frontend:

Изменить код отображения текущего языка сайта с учетом чтения локали пользователя, передаваемой в HTTP запросе.
Сделать некликабельным текущий язык в опциях селектора.

## Критерии приемки

Feature: Switch languages

  Scenario: User selects language
    Given I am on the main page
    When I select option "EN"
    Then I see the main headline "START SAVING YOUR COURSE TODAY!"
    When I select option "RU"
    Then I see the main headline "НАЧНИ ОБУЧЕНИЕ УЖЕ СЕГОДНЯ!"

# Расчетное время

1 час

# Затраченное время

1 час

**Comment by salvorg** [comment]
Внесены исправления выходящих в консоли ошибок
