### ISSUE TITLE
#4 - Создание структуры базового проекта.

### ISSUE THREAD

**Issue by aibeksaaliev** [ESDP-JS17-ATTRACTOR/final#4]
**#Мотивация#**

После первой встречи с заказчиком от 05.04.2023 и обсуждений с командой от 06.04.2023-07.04.2023 было решено поднять проект.

**#Решение#**

Создать директорию для проекта командой (mkdir), перейти в эту директорию.
В консоли прописать следующие команды для создания frontend приложения на NextJS:

1. npx create-next-app@latest front --typescript
1.1 Добавить ESLint для использования проекта.
1.2 Отказаться от Tailwind CSS для использования в проекте.
1.3 Добавить директорию src/ в проект.
1.4 Отказаться от директории app/ в проекте.
1.5 Не импортировать alias configuration.
2. Перейти в директорию front и удалить папку .git (rm -rf .git).
3. В файл .gitignore добавить папки .idea, node_modules и файл .env

Последующие зависимости для frontend приложения будут вынесены на обсуждения с командой.

Выйти из директории front и в основной директории проекта для создания backend приложения прописать в консоли следующие команды:

1. nest new back
2. Перейти в директорию back и установить следующие зависимости через npm i:
2.1 @nestjs/typeorm typeorm
2.2 pg
2.3 bcrypt
3. В этой же директории back удалить папку .git (rm -rf .git).
4. В файл .gitignore добавить папки .idea, node_modules и файл .env

Последующие зависимости для backend приложения будут вынесены на обсуждения с командой.

Выйти из директории back, и в основной директории проекта проинициализировать git. В консоли прописать следующие команды:

1. git init
2. git add -A
3. git commit -m "#4 - Creating a basic project structure"

#Критерий приемки#

Выполнить проверку на наличие всех зависимостей в файле package.json, а также всех ненужных папок и файлов в файлах .gitignore.

**Comment by salvorg** [comment]
#4 Created a basic project structure.
